### ISSUE TITLE
Alguns testes estão dando erro ao rodar sem interface, segue lista abaixo do nome do teste e do erro:

### ISSUE THREAD

**Issue by Carlos3du** [LucasGdBS/PuppyCore#21]
- **teste_alterar_cadastro_pet** -> Dando erro no assert
- **teste_dados_alterar_preenchidos_pet** -> Dando erro no assert
- **teste_ver_info_pet** -> Erro no comando de click
- **teste_ver_pets** -> Erro no comando de clicar no elemento
- **teste_ver_info_tutor** -> Não está achando o tutor pra clicar

**Comment by LucasGdBS** [comment]
Ajeitei 2, tem 
- teste_alterar_cadastro_pet
- teste_ver_info_tutor
- teste_ver_pets
